test: face.mdl lex.py main.py matrix.py mdl.py display.py draw.py gmath.py yacc.py
	python2 main.py face.mdl

clean:
	shred -u *pyc *out parsetab.py *.png

clear:
	shred -u *pyc *out parsetab.py *ppm *.png
